version: 1
disable_existing_loggers: false

formatters:
  ce_format:
    format: '%(message)s'
    class: logger.format.CeFormat
  simple:
    format: "%(asctime)s - %(filename)s -%(name)s -%(levelname)s - %(message)s"

handlers:
  ce_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: ce_format
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: ce_format
    filename: ${LOG_PATH}
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  dev:
    level: DEBUG
    handlers: [ce_console]
    propagate: false
  gray:
    level: INFO
    handlers: [ce_console, file]
    propagate: false
  production:
    level: INFO
    handlers: [ce_console, file]
    propagate: false

